sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
  - bash install.sh
script:
  - source env.sh && npm run test
notifications:
  slack: devops-training-spb:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  provider: heroku
  api_key:
    secure: kxFv3d8HyBS7TQan3Gu+verRQuRSCzEpRxWgn8L57ktUznGX0PXiUFcrMmsAymZkSK9q6znvkDSLj6liCqqTybKlAzT4AvbdPkw1YWGBIR+j2JVGQr8M9kWxhDHggpTG1EQRvQFTfvNqgsjGuCUzJmZpNbRcaAm2HB5F8kNsgWES/OmJn9/tO9V/j9HH8aPYOrYdHuzUc2kokGEpQjIiV0qkX6WDAtodE1HIbOAifseEq2AVp8jh/ZTLVB9kByZZiqNl/T0jzOR+ebWXe0f9kzh43wMv8/IFcrPhTM4cCPmV8gGc0X9WVu1eHYbk3BOly/D8EBpk50OV6YT+RjtLPhbQAR+HSTbjQVOBQCoPBzu2bxsWyxm3mbpuVqpTOcNh58yh/OVPBr84BiY0zUJZOYF4pqL1BAdlqIoH1iu8bt6dbxmhUndowjR1MEeUK9htOxMWyXfZ6CrSYD2bTGi7ldVa9xRxesZORdB2O3OduhUjk0mgIbWqN22U499wn4xg8UvLHKSPAABA54+inS5orvsToOsIy2aZ0p8OgZipvOYNya4+vI5SW9UUt/gpNX52mDbMobuPwfYm+pacRDFbB6lsuxx5ZTFrp7inf0f/zscw8jBFZeTS5H0d6MvGwP3v2G/hZSLKHVAxOQ+cVhhdP0bzxUf+PDdTjdYgdCKrvr4=
  app: tranquil-gorge-94876
  on:
    repo: nikzakharov/delivery-pipeline-training
