sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
  - bash install.sh
script:
  - source env.sh && npm run test
notifications:
  slack: devops-training-spb:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  provider: heroku
  api_key:
    secure: jwf4zNXPUl81mmPwYv3LyNUo44KTxdACuHHHRmTo6IeEvq9VjS+cz+BRvA6WLQ49yCb4rMpvUewGGO+EOGdG6sqnMVmvqYv6PgKJOoZJ8tdi2pDOOYsQcsX8R3sGWDZGytVFVdsM5pK2RNr6mCVpZ180ZmKwKAJEhZOWPWp8BH5nec1Kn44YNKI9KNv40sr9HL0w5hAH3P4VIcXpoOBQuBMYmKa46fYgP5KdERwBKgZiaEu9yxMrIBAoG3HCjMDkGdfIR518o1Rr8ZPGIawSMODLDUd7VZfUw20ZESheY1KjSlCU3WS7yXQ8kuCtHrBZiEo9kbXWffgrNEMDl0bpNVirG4WQgtgmkG8l4hoUNKePa3pY9TsJVKXuigbWSaO1DJtR/F/FL822y/tg77YGxFv18hjtMNBayNFCj2in9VwJ1BZaqW7CNDL2hMSMWNpcK7O8PSnYMvl8jaKj+GBCUTtUiOG3Zm50p0BgfckcZXkXDqhG4rpbF2QwzXxUGalng+gU0MEQmBZj3gnlCqEQzDGL1eulvvVQZJApO0HwGjXMSllU8Kxc92BwzgJ/EHzh+PpK/QP7Z9Db2Flxaj4Oocy3ZUK9byCU6BCbEFSW/d4A0QewDRtH2KHf29dfM7KGveVyOtfysDJ7mbWAXc21D+lnoMSwwXT5o38bJoTsGgY=
  app: tranquil-gorge-94876
