sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
  - bash install.sh
script:
  - source env.sh && npm run test
notifications:
  slack: devops-training-spb:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  app: pumpkin-tart-71750
  provider: heroku
  api_key:
    secure: PJYWZiWO/Zc3UJNA84SU+E21DVfOrl2uOhHqs8t0xPYUsF81WKjM2JNAFOfXQvaTQM0mv9bBaAFwMDLd9JAAVvX6ufy45yV6qRnUH53zPjmtyM5F9jCRUcyQ2DKIAnLQnAWb2gQpNrEFv58m54T6+tHlXaeV+yDB9Bx11lcLafLzrpGK2UXke18rx7tcxr1hr99lmeLGM0B+ivEi6jV69e2oGRVu4OOEPtph7ocYQUcPuF7gdWdxEkBR/8iCWZTSJjkxvfPFxL53JwH4hN31abWVQYFWjktDDfDikDxpUu9rFWv1YJH4AECxOSoHISJ3L4uqRS74Im/i7Y1RVcWU3ujEp1XqMYsUL5s+gnSuRx52uQoQ74wbkAq6Ee5N3KgfmRAyN2Z2KT4GOiictDWDltrMVfKbffToAz4xDShEX2b9nB1ns8bqK+kkz22uwwv6cTaEkI7OdgANlEVIfTYYBsb3n7FPrdCKSeNqyhS2qT26gD4Iy6GYdW6dUcbgryECyPR94y4JVMTJMfiojoL+845I4KPJiFEq5qTue8MvKHil7BxX4M0eFtVMTCyyVOz1XE6Xrt0kxGiRmaT7r9JAdBlJsT00gPOLSCVIpK8now0tJAJBPGZh4FYsGmzizikAYMZ87x/DA5PjZLk03HSzGW5GyFVBz4/v5dfzby6L2N4=
